spring.application.name=notes

# PostgreSQL Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/challenge_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=challenge_user
spring.datasource.password=challenge_password

# JPA and Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# SQL Query Tracing
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=trace